---
title: "TP53 annotation for HGG"
output: html_notebook
---

In this notebook we will annotate HGG samples with TP53 status we obtained from snv/cnv and TP53 classifier. We believe TP53 annotation will add useful information to the current known subtypes as we see TP53 mutations co-occurring with H3 mutations.

## Set up
```{r}
# Load in tidyverse functions
library(tidyverse)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
# results folder
results_dir <- file.path(
  root_dir,
  "analyses",
  "molecular-subtyping-HGG",
  "results")
```


### Required files
```{r}
# File path to data directory
tp53_status <- read_tsv(file.path(
  root_dir,
  "analyses",
  "tp53_nf1_score",
  "results",
  "tp53_altered_status.tsv"), guess_max = 100000) 

hgg_subtypes <- read_tsv(file.path(results_dir,"HGG_cleaned_all_table.tsv")) 

```

# Add tp53 status 
```{r}

tp53_status_RNA <- tp53_status %>% 
  select(-Kids_First_Biospecimen_ID_DNA) %>% 
  filter(!is.na(Kids_First_Biospecimen_ID_RNA)) %>% 
  dplyr::rename(Kids_First_Biospecimen_ID = Kids_First_Biospecimen_ID_RNA)

tp53_status_DNA <- tp53_status %>% 
  select(-Kids_First_Biospecimen_ID_RNA) %>% 
  filter(!is.na(Kids_First_Biospecimen_ID_DNA)) %>% 
  dplyr::rename(Kids_First_Biospecimen_ID = Kids_First_Biospecimen_ID_DNA)

tp53_status_long <- bind_rows(tp53_status_RNA, tp53_status_RNA)

hgg_subtypes_2 <- hgg_subtypes %>%
  left_join(tp53_status_long, by=c("sample_id" = "sample_id", 
                              "Kids_First_Biospecimen_ID" = "Kids_First_Biospecimen_ID")) %>%
  rename("tp53_SNV_indel_counts"="SNV_indel_counts",
         "tp53_CNV_loss_counts"="CNV_loss_counts",
         "tp53_HGVSp_Short"="HGVSp_Short" , 
         "tp53_CNV_loss_evidence"="CNV_loss_evidence",
         "tp53_hotspot"="hotspot",
         "tp53_activating"="activating",
         "tp53_Fusion_counts"="Fusion_counts", 
         "tp53_Fusion_evidence"="Fusion_evidence") %>%
  mutate(molecular_subtype= case_when(
    tp53_altered %in% c("activated", "loss") ~ stringr::str_c(molecular_subtype,", TP53"),
    TRUE ~ molecular_subtype
  )) %>%
  # update samples with duplicate subtypes
  mutate(molecular_subtype = case_when(id == "7316-9066_Solid Tissue" ~ "DMG, H3 K28, TP53",
                                       id %in% c("7316-9013_Solid Tissue",
                                                 "7316-6477_Solid Tissue",
                                                 "7316-6477_Derived Cell Line_Serum-free_11") ~ "HGG, H3 wildtype, TP53",
                                       TRUE ~ molecular_subtype)) %>%
  arrange(Kids_First_Participant_ID, sample_id) %>%
  write_tsv(file.path(results_dir,"HGG_molecular_subtype_tp53.tsv"))

```
