---
title: "Tables output for manuscript"
author: "Aditya Lahiri, Jo Lynne Rokita"
date: "2021-2024"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
params:
  release: v15
---

Code adapted from: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd

```{r setup, include=FALSE}
library(tidyverse)
library(openxlsx)
```

## Histologies File README and excel version

This Rmarkdown generates tables used in the manuscript, including both main text and supplementary material. 

```{r define directories and result files}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
working_dir <- file.path(root_dir, "tables")
input_dir <- file.path(working_dir, "input")
analyses_dir <- file.path(root_dir, "analyses")
# Define data_dir based on ci. The `testing` param covers if we are in CI where 1 is CI.
if (params$release == "testing") {
  data_dir <- file.path(root_dir, "data")
} else {
  data_dir <- file.path(root_dir, "data", params$release)
}
results_dir <- file.path(working_dir, "results")
if(!dir.exists(results_dir)){
  dir.create(results_dir, recursive=TRUE)
}
```


# Define input files
```{r}
histology_file <- file.path(data_dir, "histologies.tsv")
```

# Define output files and sheet names, when appropriate
```{r}
table_s1_file <- file.path(results_dir, "SuppTable1-Histologies.xlsx")
```

# Read files
```{r}
histology_df <- read_tsv(histology_file, guess_max =100000)
```

## Table S1: histologies table

```{r}
readme <- tribble(
~`Histology column`,~Definition,~`Possible values`,
"age_at_chemo_start","Patient age at chemotherapy start in days","numeric",
"age_at_diagnosis_days","Patient age at diagnosis in days","numeric",
"age_at_event_days","Patient age at sample collection event in days","numeric",
"age_at_radiation_start","Patient age at radiation start in days","numeric",
"age_last_update_days","Patient age at the last clinical event/update in days","numeric",
"aliquot_id","External aliquot identifier","alphanumeric",
"broad_histology","Broad WHO classification of cancer type",paste(unique(histology_df$broad_histology), collapse = "; "),
"cancer_group","Harmonized cancer groupings for plots",paste(unique(histology_df$cancer_group), collapse = "; "),
"cancer_predispositions","Reported cancer predisposition syndromes",paste(unique(histology_df$cancer_predispositions), collapse = "; "),
"cell_line_composition","Cell line media",paste(unique(histology_df$cell_line_composition), collapse = "; "),
"cell_line_passage","Cell line passage at collection","numeric",
"clinical_status_at_event","Patient status at the time of sample collection", paste(unique(histology_df$clinical_status_at_event), collapse = "; "),
"CNS_region","Harmonized brain region based on `primary_site`",paste(unique(histology_df$CNS_region), collapse = "; "),
"cohort","Scientific cohort",paste(unique(histology_df$cohort), collapse = "; "),
"cohort_participant_id","Scientific cohort participant ID","C#####-C######",
"composition","Sample composition",paste(unique(histology_df$composition), collapse = "; "),
"dkfz_v11_methylation_subclass","v11b6 DKFZ methylation-based CNS tumor subclass","text",
"dkfz_v11_methylation_subclass_score","v11b6 DKFZ methylation-based CNS tumor subclass score","numeric",
"dkfz_v12_methylation_subclass","v12b6 DKFZ methylation-based CNS tumor subclass score","text",
"dkfz_v12_methylation_subclass_score","v12b6 DKFZ methylation-based CNS tumor subclass","numeric",
"dkfz_v12_methylation_mgmt_status","v12b6 DKFZ MGMT promoter methylation status",paste(unique(histology_df$dkfz_v11_methylation_subclass), collapse = "; "),
"dkfz_v12_methylation_mgmt_estimated","v12b6 DKFZ MGMT promoter methylation fraction","numeric",
"EFS_days","Event-free survival in days","numeric",
"EFS_event_type", "Event considered when calculating EFS", paste(unique(histology_df$EFS_event_type), collapse = "; "),
"ethnicity","Patient reported ethnicity",paste(unique(histology_df$ethnicity), collapse = "; "),
"experimental_strategy","Sequencing strategy",paste(unique(histology_df$experimental_strategy), collapse = "; "),
# leaving this non-programmatic because of the duplicates that would come up (eg two selections in one patient, needing data cleanup)
"extent_of_tumor_resection","Amount of tumor resected at time of surgical event","Biopsy only;Partial resection;Gross/Near total resection;Not Reported;Unavailable",
"germline_sex_estimate","Predicted sex of patient based on germline X and Y ratio calculation (described in methods)",paste(unique(histology_df$germline_sex_estimate), collapse = "; "),
"gtex_group","Tissue Type",paste(unique(histology_df$gtex_group), collapse = "; "),
"gtex_subgroup","Tissue Subtype",paste(unique(histology_df$gtex_subgroup), collapse = "; "),
"harmonized_diagnosis","`integrated_diagnosis` if exists or updated and harmonized diagnosis using pathology_free_text_diagnosis information","text",
"integrated_diagnosis","WHO 2021 diagnosis integrated from pathology diagnosis and molecular subtyping","text",
"Kids_First_Biospecimen_ID","Biospecimen identifier, Kids First or other cohort","BS_########",
"Kids_First_Participant_ID","Patient identifier, Kids First or other cohort","PT_########",
"match_id", "ID used to match experimental strategies within an event per sample composition", "Concatenation of sample_id, tumor descriptor, composition, and cell line composition and passage if applicable",
"molecular_subtype","Molecular subtype defined by WHO 2021 guidelines","text",
"molecular_subtype_methyl","DKFZ v12b6 or NIH v2 methylation class aligned to WHO 2021 subtypes","text",
"NIH_v2_methylation_Superfamily", "NIH Bethesda CNS v2 methylation superfamily", "text",
"NIH_v2_methylation_Superfamily_mean_score", "NIH Bethesda CNS v2 methylation superfamily score", "text",
"NIH_v2_methylation_Superfamily_Consistency_score", "NIH Bethesda CNS v2 methylation superfamily consistency score", "text",
"NIH_v2_methylation_Class", "NIH Bethesda CNS v2 methylation subtype", "text",
"NIH_v2_methylation_Class_mean_score", "NIH Bethesda CNS v2 methylation subtype score", "text",
"NIH_v2_methylation_Class_consistency_score", "NIH Bethesda CNS v2 methylation subtype consistency score", "text",
"NIH_v2_methylation_Superfamily_match", "NIH Bethesda CNS v2 methylation superfamily match",paste(unique(histology_df$NIH_v2_methylation_Superfamily_match), collapse = "; "),
"NIH_v2_methylation_Class_match", "NIH Bethesda CNS v2 methylation class match",paste(unique(histology_df$NIH_v2_methylation_Class_match), collapse = "; "),
"normal_fraction","Theta2 normal DNA fraction estimate","numeric",
"Notes","Free text field describing changes from `pathology_diagnosis` to `integrated_diagnosis` or manner in which molecular_subtype was determined","text",
"OS_days","Overall survival in days","numeric",
"OS_status","Overall survival status",paste(unique(histology_df$OS_status), collapse = "; "),
"pathology_diagnosis","Reported and/or harmonized patient diagnosis from pathology reports","text",
"pathology_free_text_diagnosis","Free text patient diagnosis from pathology reports","text",
"primary_site","Bodily site(s) from which specimen was derived","text",
"race","Patient reported race",paste(unique(histology_df$race), collapse = "; "),
"reported_gender","Patient reported gender",paste(unique(histology_df$reported_gender), collapse = "; "),
"RNA_library","Type of RNA-Sequencing library preparation",paste(unique(histology_df$RNA_library), collapse = "; "),
"sample_id","Event id","alphanumeric",
"sample_type","Broad sample type",paste(unique(histology_df$sample_type), collapse = "; "),
"seq_center","Sequencing center",paste(unique(histology_df$seq_center), collapse = "; "),
"short_histology","Abbreviated `cancer_group` or `broad_histology` for plotting purposes",paste(unique(histology_df$short_histology), collapse = "; "),
"sub_cohort", "sub-cohort", paste(unique(histology_df$sub_cohort), collapse = "; "),
"tumor_descriptor","Phase of therapy from which tumor was derived",paste(unique(histology_df$tumor_descriptor), collapse = "; "),
"tumor_fraction","Theta2 tumor DNA fraction estimate","numeric",
"tumor_fraction_LUMP","LUMP tumor DNA fraction estimate from methylation","numeric",
"tumor_fraction_RFpurify_ABSOLUTE","RFpurify ABSOLUTE tumor DNA fraction estimate from methylation","numeric",
"tumor_fraction_RFpurify_ESTIMATE","RFpurify ESTIMATE tumor DNA fraction estimate from methylation","numeric",
"tumor_ploidy","Control-FREEC ploidy estimate","numeric"
)

# Combine and output
list_s1_table <- list(README = readme,
                      histologies_file = histology_df)
write.xlsx(list_s1_table, 
           table_s1_file, 
           overwrite=TRUE, 
           keepNA=TRUE)
```
