name: Build and Push

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'Dockerfile'

jobs:
  build_and_publish_image:
    name: Build and Publish Image
    runs-on: large-runner-32
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pgc-images.sbgenomics.com/rokita-lab/openpedcanverse
          tags: |
            type=raw,value=latest
            # Only tag the image with latest if we're building on the default
            # branch (e.g., main).
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: pgc-images.sbgenomics.com
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: github_pat=${{ secrets.GITHUB_TOKEN }}
