name: Build

on:
  pull_request:

jobs:
  build_only:
    name: Build Only
    runs-on: large-runner-32
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pgc-images.sbgenomics.com/rokita-lab/openpedcanverse
          tags: |
            type=raw,value=analysisjob
            # Only tag the image with latest if we're building on the default
            # branch (e.g., main).
            type=raw,value=analysisjob,enable={{is_default_branch}}

      - name: Login to CAVATICA Docker registry
        uses: docker/login-action@v3
        with:
          registry: pgc-images.sbgenomics.com
          username: ${{ secrets.CAVATICA_USERNAME }}
          password: ${{ secrets.CAVATICA_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: github_pat=${{ secrets.GITHUB_TOKEN }}
