name: Analysis

on:
  pull_request:

jobs:
  consensus_cn_manta:
    name: Run Analysis - Consensus CN Manta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Download Data for Consensus CN Manta
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: ./download-data.sh
        env:
          OPENPEDCAN_URL: https://s3.amazonaws.com/bti-openaccess-us-east-1-prd-opc
          OPENPEDCAN_RELEASE: testing
      - name: Run Consensus CN Manta
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: ./analyses/copy_number_consensus_call_manta/run_consensus_call.sh
  
  consensus_cn:
    name: Run Analysis - Consensus CN
    needs: consensus_cn_manta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Download Data for Consensus CN
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: ./download-data.sh
        env:
          OPENPEDCAN_URL: https://s3.amazonaws.com/bti-openaccess-us-east-1-prd-opc
          OPENPEDCAN_RELEASE: testing
      - name: Run Consensus CN
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: ./analyses/copy_number_consensus_call/run_consensus_call.sh

  run_analysis:
    name: Run Analysis
    runs-on: ubuntu-latest-m
    strategy:
      fail-fast: false
      matrix:
        include:
          # Molecular subtyping modules
          - name: Molecular Subtyping - MB
            entrypoint: molecular-subtyping-MB/run-molecular-subtyping-mb.sh
            openpbta_subset: 0

          - name: Molecular Subtyping - CRANIO
            entrypoint: molecular-subtyping-CRANIO/run-molecular-subtyping-cranio.sh
            openpbta_subset: 0

          - name: Molecular Subtyping - EPN
            entrypoint: molecular-subtyping-EPN/run-molecular-subtyping-EPN.sh

          - name: Molecular Subtyping - EMBRYONAL
            entrypoint: molecular-subtyping-embryonal/run-embryonal-subtyping.sh
            openpbta_testing: 1

          - name: Molecular Subtyping - CHORDOMA
            entrypoint: molecular-subtyping-chordoma/run-molecular-subtyping-chordoma.sh
            openpbta_subset: 0

          - name: Molecular Subtyping - EWS
            entrypoint: molecular-subtyping-EWS/run_subtyping.sh

          - name: Molecular Subtyping - NEUROCYTOMA
            entrypoint: molecular-subtyping-neurocytoma/run_subtyping.sh

          - name: Molecular Subtyping - HGG
            entrypoint: molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh

          - name: Molecular Subtyping - LGG
            entrypoint: molecular-subtyping-LGAT/run_subtyping.sh
            openpbta_subset: 0
            
          - name: Molecular Subtyping - ATRT
            entrypoint: molecular-subtyping-ATRT/run-molecular-subtyping-ATRT.sh
            
          - name: Molecular Subtyping - PB
            entrypoint: molecular-subtyping-PB/run-molecular-subtyping-PB.sh
            
          - name: Molecular Subtyping - NBL
            entrypoint: molecular-subtyping-NBL/run-molecular-subtyping-NBL.sh

          - name: Molecular Subtyping - PATHOLOGY/COMPILE
            entrypoint: molecular-subtyping-pathology/run-subtyping-aggregation.sh
            openpbta_testing: 1

          - name: Molecular Subtyping - INTEGRATE (+ add cancer groups)
            entrypoint: molecular-subtyping-integrate/run-subtyping-integrate.sh
            

          # Analysis modules
          - name: Independent Specimens
            entrypoint: independent-samples/run-independent-samples.sh

          - name: Independent Specimens pre-release
            entrypoint: independent-samples/run-independent-samples.sh
            run_for_subtyping: 1

          - name: Gene set enrichment
            entrypoint: gene-set-enrichment-analysis/run-gsea.sh
            run_for_subtyping: 1
            openpbta_testing: 1

          - name: TP53/NF1 scores
            entrypoint: tp53_nf1_score/run_classifier.sh
            openpedcan_polya_strand: 0

          - name: Fusion filtering
            entrypoint: fusion_filtering/run_fusion_merged.sh

          - name: Fusion summary
            entrypoint: fusion-summary/run-new-analysis.sh
            openpbta_subset: 0

          - name: Consensus CN Manta
            entrypoint: copy_number_consensus_call_manta/run_consensus_call.sh

          - name: Consensus CN
            entrypoint: copy_number_consensus_call/run_consensus_call.sh

          - name: Consensus CN annotation
            entrypoint: focal-cn-file-preparation/run-prepare-cn.sh
            openpbta_testing: 1

          - name: TMB calculation
            entrypoint: tmb-calculation/run_tmb_calculation.sh
            
          - name: Mutational signatures
            entrypoint: mutational-signatures/run_mutational_signatures.sh
            openpbta_testing: 1

          - name: Immune Deconvolution
            entrypoint: immune-deconv/run-immune-deconv.sh

          #- name: EFO/MONDO annotation
          #  entrypoint: efo-mondo-mapping/run_search_and_qc.sh

          #- name: ENSEMBL Gene matching
          #  entrypoint: gene_match/run-gene-mapping.sh

          #- name: Update table annotation data
          #  entrypoint: long-format-table-utils/run-update-long-format-table-utils.sh

          #- name: RNA-Seq Expression Summary stats
          #  entrypoint: rna-seq-expression-summary-stats/run-rna-seq-expression-summary-stats.sh

          # MTP-specific modules
          #- name: Fusion frequency tables
          #  entrypoint: fusion-frequencies/run-frequencies.sh

          #- name: SNV frequency tables
          #  entrypoint: snv-frequencies/run-snv-frequencies.sh

          #- name: CNV frequency tables
          #  entrypoint: cnv-frequencies/run-cnv-frequencies-analysis.sh
            
          #- name: RNA-Seq batch correction
          #  entrypoint: rnaseq-batch-correct/run_ruvseq.sh

    steps:
      - uses: actions/checkout@v4
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Download Data
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: ./download-data.sh
        env:
          OPENPEDCAN_URL: https://s3.amazonaws.com/bti-openaccess-us-east-1-prd-opc
          OPENPEDCAN_RELEASE: testing

      - name: Run Analysis
        uses: docker://pgc-images.sbgenomics.com/rokita-lab/openpedcanverse:latest
        with:
          entrypoint: analyses/${{ matrix.entrypoint }}
        env:
          OPENPBTA_SUBSET: ${{ matrix.openpbta_subset }}
          OPENPBTA_TESTING: ${{ matrix.openpbta_testing }}
          RUN_FOR_SUBTYPING: ${{ matrix.run_for_subtyping }}
          OPENPEDCAN_POLYA_STRAND: ${{ matrix.openpedcan_polya_strand }}
          